sp_blog_config:
    resource: "@SpBarBlogBundle/Resources/config/backend/config_route.yml"
    prefix:   /config

sp_blog_theme:
    resource: "@SpBarBlogBundle/Resources/config/backend/theme_route.yml"
    prefix:   /theme

sp_blog_post:
    resource: "@SpBarBlogBundle/Resources/config/backend/post_route.yml"
    prefix:   /post
