services:
    spbar.user_registration_form_type:
        class: SpBar\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: spbar_user_registration }

    spbar.user_profile_form_type:
        class: SpBar\Bundle\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: spbar_user_profile }

    spbar.user_change_password_form_type:
        class: SpBar\Bundle\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: spbar_user_change_password }

    spbar.user_group_form_type:
        class: SpBar\Bundle\UserBundle\Form\Type\GroupFormType
        tags:
            - { name: form.type, alias: spbar_user_group }

    spbar.user_access:
        class: SpBar\Bundle\UserBundle\Utility\Permission
        arguments: [@service_container]