blog_admin:
    resource: "@BlogAdminBundle/Resources/config/routing.yml"
    prefix:   /

blog_public:
    resource: "@BlogPublicBundle/Resources/config/routing.yml"
    prefix:   /public

blog_post:
    resource: "@BlogPostBundle/Resources/config/routing.yml"
    prefix:   /

# blog_user:
#     resource: "@BlogUserBundle/Resources/config/routing.yml"
#     prefix:   /

logout:
    path: /logout


sp_blog:
    resource: "@SpBarBlogBundle/Resources/config/routing.yml"

sp_userbundle:
    resource: "@SpBarUserBundle/Resources/config/routing.yml"

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
