sp_user_frontend_login: 
    path: /login
    defaults: { _controller: SpBarUserBundle:Frontend/PublicSecurity:login }

sp_user_frontend_login_check:
    path: /login_check
    defaults: { _controller: SpBarUserBundle:Frontend/PublicSecurity:check }