sp_user_index:
    path: /
    defaults: { _controller:SpBarUserBundle:User:index }

sp_user_list:
    path: /list/
    defaults: { _controller:SpBarUserBundle:User:list }

sp_user_new:
    path: /new/
    defaults: { _controller:SpBarUserBundle:Registration:register }

sp_user_edit:
    path: /sp-{user}/edit/
    defaults: { _controller:SpBarUserBundle:User:edit }

sp_user_delete:
    path: /sp-{user}/delete/
    defaults: { _controller:SpBarUserBundle:User:delete }

sp_user_enable:
    path: /sp-{user}/enable/
    defaults: { _controller:SpBarUserBundle:User:enable }


